package fleet;
// Generated 20 Jan, 2020 2:21:04 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Amenity generated by hbm2java
 */
@Entity
@Table(name = "amenity", catalog = "fleet_management")
public class Amenity implements java.io.Serializable {

	private int amenitiesid;
	private String amenitiesname;
	private Integer amenitiesrate;

	public Amenity() {
	}

	public Amenity(int amenitiesid) {
		this.amenitiesid = amenitiesid;
	}

	public Amenity(int amenitiesid, String amenitiesname, Integer amenitiesrate) {
		this.amenitiesid = amenitiesid;
		this.amenitiesname = amenitiesname;
		this.amenitiesrate = amenitiesrate;
	}

	@Id

	@Column(name = "amenitiesid", unique = true, nullable = false)
	public int getAmenitiesid() {
		return this.amenitiesid;
	}

	public void setAmenitiesid(int amenitiesid) {
		this.amenitiesid = amenitiesid;
	}

	@Column(name = "amenitiesname", length = 256)
	public String getAmenitiesname() {
		return this.amenitiesname;
	}

	public void setAmenitiesname(String amenitiesname) {
		this.amenitiesname = amenitiesname;
	}

	@Column(name = "amenitiesrate")
	public Integer getAmenitiesrate() {
		return this.amenitiesrate;
	}

	public void setAmenitiesrate(Integer amenitiesrate) {
		this.amenitiesrate = amenitiesrate;
	}

}
