package fleet;
// Generated 20 Jan, 2020 2:21:04 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Billing generated by hbm2java
 */
@Entity
@Table(name = "billing", catalog = "fleet_management")
public class Billing implements java.io.Serializable {

	private int billid;
	private Hub hubByDropofflocation;
	private Employee employee;
	private Hub hubByPickuplocation;
	private Date startdate;
	private Date enddate;
	private String billfirstname;
	private String billlastname;
	private String address;
	private String aadharno;
	private String phoneno;
	private Long dailyrate;
	private Long weeklyrate;
	private Long monthlyrate;
	private String fuelstatus;
	private String bstatus;
	private String amenitiesname;
	private Long amenitiesrate;
	private Date bdob;
	private long totalbill;

	public Billing() {
	}

	public Billing(int billid, Hub hubByDropofflocation, Employee employee, Hub hubByPickuplocation, long totalbill) {
		this.billid = billid;
		this.hubByDropofflocation = hubByDropofflocation;
		this.employee = employee;
		this.hubByPickuplocation = hubByPickuplocation;
		this.totalbill = totalbill;
	}

	public Billing(int billid, Hub hubByDropofflocation, Employee employee, Hub hubByPickuplocation, Date startdate,
			Date enddate, String billfirstname, String billlastname, String address, String aadharno, String phoneno,
			Long dailyrate, Long weeklyrate, Long monthlyrate, String fuelstatus, String bstatus, String amenitiesname,
			Long amenitiesrate, Date bdob,long totalbill) {
		this.billid = billid;
		this.hubByDropofflocation = hubByDropofflocation;
		this.employee = employee;
		this.hubByPickuplocation = hubByPickuplocation;
		this.startdate = startdate;
		this.enddate = enddate;
		this.billfirstname = billfirstname;
		this.billlastname = billlastname;
		this.address = address;
		this.aadharno = aadharno;
		this.phoneno = phoneno;
		this.dailyrate = dailyrate;
		this.weeklyrate = weeklyrate;
		this.monthlyrate = monthlyrate;
		this.fuelstatus = fuelstatus;
		this.bstatus = bstatus;
		this.amenitiesname = amenitiesname;
		this.amenitiesrate = amenitiesrate;
		this.bdob = bdob;
		this.totalbill = totalbill;
	}

	@Id

	@Column(name = "billid", unique = true, nullable = false)
	public int getBillid() {
		return this.billid;
	}

	public void setBillid(int billid) {
		this.billid = billid;
	}

	@Transient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dropofflocation", nullable = false)
	public Hub getHubByDropofflocation() {
		return this.hubByDropofflocation;
	}

	public void setHubByDropofflocation(Hub hubByDropofflocation) {
		this.hubByDropofflocation = hubByDropofflocation;
	}

	@Transient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employeeempid", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Transient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pickuplocation", nullable = false)
	public Hub getHubByPickuplocation() {
		return this.hubByPickuplocation;
	}

	public void setHubByPickuplocation(Hub hubByPickuplocation) {
		this.hubByPickuplocation = hubByPickuplocation;
	}

	@JsonFormat(shape=JsonFormat.Shape.STRING,pattern="dd-MM-yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name = "startdate", length = 10)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@JsonFormat(shape=JsonFormat.Shape.STRING,pattern="dd-MM-yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name = "enddate", length = 10)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "billfirstname", length = 256)
	public String getBillfirstname() {
		return this.billfirstname;
	}

	public void setBillfirstname(String billfirstname) {
		this.billfirstname = billfirstname;
	}

	@Column(name = "billlastname", length = 256)
	public String getBilllastname() {
		return this.billlastname;
	}

	public void setBilllastname(String billlastname) {
		this.billlastname = billlastname;
	}

	@Column(name = "address", length = 256)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "aadharno", length = 45)
	public String getAadharno() {
		return this.aadharno;
	}

	public void setAadharno(String aadharno) {
		this.aadharno = aadharno;
	}

	@Column(name = "phoneno", length = 45)
	public String getPhoneno() {
		return this.phoneno;
	}

	public void setPhoneno(String phoneno) {
		this.phoneno = phoneno;
	}

	@Column(name = "dailyrate", precision = 10, scale = 0)
	public Long getDailyrate() {
		return this.dailyrate;
	}

	public void setDailyrate(Long dailyrate) {
		this.dailyrate = dailyrate;
	}

	@Column(name = "weeklyrate", precision = 10, scale = 0)
	public Long getWeeklyrate() {
		return this.weeklyrate;
	}

	public void setWeeklyrate(Long weeklyrate) {
		this.weeklyrate = weeklyrate;
	}

	@Column(name = "monthlyrate", precision = 10, scale = 0)
	public Long getMonthlyrate() {
		return this.monthlyrate;
	}

	public void setMonthlyrate(Long monthlyrate) {
		this.monthlyrate = monthlyrate;
	}

	@Column(name = "fuelstatus", length = 256)
	public String getFuelstatus() {
		return this.fuelstatus;
	}

	public void setFuelstatus(String fuelstatus) {
		this.fuelstatus = fuelstatus;
	}

	@Column(name = "bstatus", length = 256)
	public String getBstatus() {
		return this.bstatus;
	}

	public void setBstatus(String bstatus) {
		this.bstatus = bstatus;
	}

	@Column(name = "amenitiesname", length = 256)
	public String getAmenitiesname() {
		return this.amenitiesname;
	}

	public void setAmenitiesname(String amenitiesname) {
		this.amenitiesname = amenitiesname;
	}

	@Column(name = "amenitiesrate", precision = 10, scale = 0)
	public Long getAmenitiesrate() {
		return this.amenitiesrate;
	}

	public void setAmenitiesrate(Long amenitiesrate) {
		this.amenitiesrate = amenitiesrate;
	}

	@JsonFormat(shape=JsonFormat.Shape.STRING,pattern="dd-MM-yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name = "bdob", length = 10)
	public Date getBdob() {
		return this.bdob;
	}

	public void setBdob(Date bdob) {
		this.bdob = bdob;
	}

	@Column(name = "totalbill", nullable = false, precision = 10, scale = 0)
	public long getTotalbill() {
		return totalbill;
	}

	public void setTotalbill(long totalbill) {
		this.totalbill = totalbill;
	}

	@Override
	public String toString() {
		return "Billing [enddate=" + enddate + "]";
	}

	
}
