package fleet;
// Generated 20 Jan, 2020 2:21:04 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "fleet_management")
public class Employee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int empid;
	private Hub hub;
	private String empname;
	private Date empdob;
	private String empaddress;
	private String empphoneno;
	private String empemailid;
	private String emppanno;
	private Set<Billing> billings = new HashSet<Billing>(0);

	public Employee() {
	}

	public Employee(int empid, Hub hub) {
		this.empid = empid;
		this.hub = hub;
	}

	public Employee(int empid, Hub hub, String empname, Date empdob, String empaddress, String empphoneno,
			String empemailid, String emppanno, Set<Billing> billings) {
		this.empid = empid;
		this.hub = hub;
		this.empname = empname;
		this.empdob = empdob;
		this.empaddress = empaddress;
		this.empphoneno = empphoneno;
		this.empemailid = empemailid;
		this.emppanno = emppanno;
		this.billings = billings;
	}

	@Id

	@Column(name = "empid", unique = true, nullable = false)
	public int getEmpid() {
		return this.empid;
	}

	public void setEmpid(int empid) {
		this.empid = empid;
	}

	@Transient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hhubid", nullable = false)
	public Hub getHub() {
		return this.hub;
	}

	public void setHub(Hub hub) {
		this.hub = hub;
	}

	@Column(name = "empname", length = 256)
	public String getEmpname() {
		return this.empname;
	}

	public void setEmpname(String empname) {
		this.empname = empname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "empdob", length = 10)
	public Date getEmpdob() {
		return this.empdob;
	}

	public void setEmpdob(Date empdob) {
		this.empdob = empdob;
	}

	@Column(name = "empaddress", length = 256)
	public String getEmpaddress() {
		return this.empaddress;
	}

	public void setEmpaddress(String empaddress) {
		this.empaddress = empaddress;
	}

	@Column(name = "empphoneno", length = 256)
	public String getEmpphoneno() {
		return this.empphoneno;
	}

	public void setEmpphoneno(String empphoneno) {
		this.empphoneno = empphoneno;
	}

	@Column(name = "empemailid", length = 256)
	public String getEmpemailid() {
		return this.empemailid;
	}

	public void setEmpemailid(String empemailid) {
		this.empemailid = empemailid;
	}

	@Column(name = "emppanno", length = 256)
	public String getEmppanno() {
		return this.emppanno;
	}

	public void setEmppanno(String emppanno) {
		this.emppanno = emppanno;
	}

	@Transient
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<Billing> getBillings() {
		return this.billings;
	}

	public void setBillings(Set<Billing> billings) {
		this.billings = billings;
	}

}
