package fleet;
// Generated 20 Jan, 2020 2:21:04 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name = "state", catalog = "fleet_management")
public class State implements java.io.Serializable {

	private int stateid;
	private String statename;
	private Set<City> cities = new HashSet<City>(0);

	public State() {
	}

	public State(int stateid) {
		this.stateid = stateid;
	}

	public State(int stateid, String statename, Set<City> cities) {
		this.stateid = stateid;
		this.statename = statename;
		this.cities = cities;
	}

	@Id

	@Column(name = "stateid", unique = true, nullable = false)
	public int getStateid() {
		return this.stateid;
	}

	public void setStateid(int stateid) {
		this.stateid = stateid;
	}

	@Column(name = "statename", length = 45)
	public String getStatename() {
		return this.statename;
	}

	public void setStatename(String statename) {
		this.statename = statename;
	}

	//@Transient
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER/*, mappedBy = "state"*/)
	@JoinColumn(name = "statestateid", referencedColumnName="stateid")
	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

}
